In [1]:
import pandas as pd
import numpy as np
# from matplotlib import pyplot as plt

In [2]:
na_val=['Missing','None','NA']
df=pd.read_csv('C:/Users/hp/Downloads/books_1.Best_Books_Ever.csv',na_values=na_val)

In [3]:
pd.set_option('display.max_column',25)

In [4]:
df.isnull().sum()

bookId                  0
title                   2
series              29008
author                  0
rating                  0
description          1338
language             3806
isbn                    0
genres                  0
characters              0
bookFormat           1473
edition             47523
pages                2347
publisher            3696
publishDate           880
firstPublishDate    21326
awards                  0
numRatings              0
ratingsByStars          0
likedPercent          622
setting                 0
coverImg              605
bbeScore                0
bbeVotes                0
price               14365
dtype: int64

In [5]:
df['pages']=df['pages'].str.replace(r'\D+',' ',regex=True)

In [6]:
df['pages']=df['pages'].astype(float)

In [7]:
df['pages'].mean()

np.float64(328.51453192635296)

In [8]:
df['pages']=df['pages'].fillna(df['pages'].median())

In [9]:
df['pages']=df['pages'].astype(int)

In [10]:
#check for the outliners
df.sort_values(by='pages',inplace=True)
def checkcoutlinears(df,col):
    Q1=df[col].quantile(0.25)
    Q3=df[col].quantile(0.75)
    IQR=Q3-Q1
    lower =Q1-1.5*IQR
    upper=Q3+1.5*IQR
    outliner=df[(df[col]<lower) | (df[col]>upper)]
    return outliner

In [11]:
outliners=checkcoutlinears(df,'pages')

In [12]:
filt=df['pages']>1300

In [13]:
df.loc[filt,['pages']]=1#setting the values to 1 more than 1300
filt.sum()

np.int64(306)

In [14]:
outliners['pages'].describe()

count     2549.000000
mean       985.891330
std        695.372517
min        638.000000
25%        695.000000
50%        792.000000
75%       1008.000000
max      14777.000000
Name: pages, dtype: float64

In [15]:
df.sort_index(inplace=True)

In [16]:
filt=(df['pages']<=433)
filt2=df['pages']>=866
filt3=(df['pages']>433)& (df['pages']<=866)

In [17]:
df.loc[filt,'length']='Short Book'
df.loc[filt2,'length']='Long Book'
df.loc[filt3,'length']='Standard Book'

In [18]:
df['length'].value_counts()

length
Short Book       43969
Standard Book     7850
Long Book          659
Name: count, dtype: int64

In [19]:
df.isnull().sum()

bookId                  0
title                   2
series              29008
author                  0
rating                  0
description          1338
language             3806
isbn                    0
genres                  0
characters              0
bookFormat           1473
edition             47523
pages                   0
publisher            3696
publishDate           880
firstPublishDate    21326
awards                  0
numRatings              0
ratingsByStars          0
likedPercent          622
setting                 0
coverImg              605
bbeScore                0
bbeVotes                0
price               14365
length                  0
dtype: int64

In [20]:
df['price'].tail(50)

52428     5.41
52429    17.37
52430     1.38
52431      NaN
52432      NaN
52433     7.03
52434     4.22
52435     3.12
52436      NaN
52437     3.89
52438     5.43
52439     3.59
52440      NaN
52441    23.04
52442     2.69
52443     3.13
52444     1.12
52445     1.45
52446     2.91
52447     3.89
52448     3.07
52449     4.41
52450      NaN
52451     5.20
52452     3.52
52453     4.45
52454     4.00
52455     3.67
52456    13.35
52457      NaN
52458     4.99
52459     2.53
52460     2.94
52461      NaN
52462      NaN
52463    10.37
52464     8.94
52465     5.18
52466     7.92
52467      NaN
52468      NaN
52469     4.56
52470     5.55
52471      NaN
52472    19.18
52473      NaN
52474      NaN
52475     7.37
52476     2.86
52477     5.20
Name: price, dtype: str

In [21]:
df[['first','sencond','third']]=df['price'].str.split('.',expand=True)

In [22]:
df['sencond'] = df['sencond'].fillna('0')
df['third'] = df['third'].fillna('0')

In [23]:
df['sencond'].info()
df['first'].info()
df['third'].info()

<class 'pandas.Series'>
Index: 52478 entries, 0 to 52477
Series name: sencond
Non-Null Count  Dtype
--------------  -----
52478 non-null  str
dtypes: str(1)
memory usage: 820.0 KB
<class 'pandas.Series'>
Index: 52478 entries, 0 to 52477
Series name: first
Non-Null Count  Dtype
--------------  -----
38113 non-null  str
dtypes: str(1)
memory usage: 820.0 KB
<class 'pandas.Series'>
Index: 52478 entries, 0 to 52477
Series name: third
Non-Null Count  Dtype
--------------  -----
52478 non-null  str
dtypes: str(1)
memory usage: 820.0 KB

In [24]:
df['price']=df['first']+'.'+df['sencond']+df['third']

In [25]:
df['price']=df['price'].astype(float)
df['price']=df['price'].fillna(df['price'].median())
outliners2=checkcoutlinears(df,'price')

In [26]:
outliners2

,bookId,title,series,author,rating,description,language,isbn,genres,characters,bookFormat,edition,...,numRatings,ratingsByStars,likedPercent,setting,coverImg,bbeScore,bbeVotes,price,length,first,sencond,third
8,30.J_R_R_Tolkien_4_Book_Boxed_Set,J.R.R. Tolkien 4-Book Boxed Set: The Hobbit an...,The Lord of the Rings #0-3,J.R.R. Tolkien,4.60,"This four-volume, boxed set contains J.R.R. To...",English,9780345538376,"['Fantasy', 'Fiction', 'Classics', 'Adventure'...","['Frodo Baggins', 'Gandalf', 'Bilbo Baggins', ...",Mass Market Paperback,Hobbit Movie Tie-in Boxed set,...,110146,"['78217', '22857', '6628', '1477', '967']",98.0,['Middle-earth'],https://i.gr-assets.com/images/S/compressed.ph...,1159802,12111,21.15,Short Book,21,15,0
24,18144590-the-alchemist,The Alchemist,NaN,"Paulo Coelho (Goodreads Author), Alan R. Clark...",3.88,Paulo Coelho's enchanting novel has inspired a...,English,9780062315007,"['Fiction', 'Classics', 'Fantasy', 'Philosophy...","['Santiago', 'Alchemist', 'Melchizedek']",Paperback,25th Anniversary Edition,...,2107732,"['805221', '613564', '414410', '172160', '1023...",87.0,"['Egypt', 'Sahara Desert', 'Tangier (Morocco)'...",https://i.gr-assets.com/images/S/compressed.ph...,765587,8008,13.22,Short Book,13,22,0
25,7144.Crime_and_Punishment,Crime and Punishment,NaN,"Fyodor Dostoyevsky, David McDuff (Translator)",4.22,"Raskolnikov, a destitute and desperate former ...",English,9780143058144,"['Classics', 'Fiction', 'Russia', 'Literature'...","['Rodion Romanovich Raskolnikov', 'Porfiry Pet...",Paperback,Penguin Classics,...,626897,"['315090', '188181', '84074', '26493', '13059']",94.0,"['Russian Empire', 'Saint Petersburg, Russian ...",https://i.gr-assets.com/images/S/compressed.ph...,759066,7937,18.85,Standard Book,18,85,0
63,44767458-dune,Dune,Dune #1,Frank Herbert,4.23,"Set on the desert planet Arrakis, Dune is the ...",English,9780593099322,"['Science Fiction', 'Fiction', 'Fantasy', 'Cla...","['Stilgar', 'Vladimir Harkonnen', 'Duncan Idah...",Hardcover,Deluxe Edition,...,765785,"['391252', '224627', '101953', '30795', '17158']",94.0,"['Arrakis', 'Caladan', 'Giedi Prime', 'Harko',...",https://i.gr-assets.com/images/S/compressed.ph...,406837,4394,29.34,Standard Book,29,34,0
81,52892857-the-color-purple,The Color Purple,The Color Purple Collection #1,Alice Walker,4.22,Winner of the Pulitzer Prize and the National ...,English,9780143135692,"['Classics', 'Fiction', 'Historical Fiction', ...","['Nettie', 'Albert', 'Celie', 'Shug Avery', 'M...",Paperback,NaN,...,521200,"['244193', '179134', '74068', '16614', '7191']",95.0,['Georgia (United States)'],https://i.gr-assets.com/images/S/compressed.ph...,319385,3631,13.75,Short Book,13,75,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52423,5962048-the-bldgblog-book,The BLDGBLOG Book,NaN,Geoff Manaugh,4.22,"Read by millions since its launch in 2004, BLD...",English,9780811866446,"['Architecture', 'Nonfiction', 'Art', 'Design'...",[],Paperback,NaN,...,412,"['191', '146', '55', '15', '5']",95.0,[],https://i.gr-assets.com/images/S/compressed.ph...,2,1,27.70,Short Book,27,70,0
52429,20665259-did-god-really-command-genocide,Did God Really Command Genocide?: Coming to Te...,NaN,"Paul Copan, Matt Flannagan",4.18,A common objection to belief in the God of the...,NaN,9780801016226,"['Theology', 'Christian', 'Religion', 'Christi...",[],Paperback,NaN,...,114,"['47', '47', '13', '7', '0']",94.0,[],https://i.gr-assets.com/images/S/compressed.ph...,2,1,17.37,Short Book,17,37,0
52441,2249571.Angel,"Angel: After the Fall, Volume 1",Angel: After the Fall #1,"Brian Lynch, Joss Whedon (Plotting), Franco Ur...",3.77,"In Angel's final television season, his world ...",English,9781600101816,"['Graphic Novels', 'Comics', 'Fantasy', 'Vampi...",['Angel'],Hardcover,NaN,...,4026,"['999', '1535', '1141', '284', '67']",91.0,"['Los Angeles, California (United States)']",https://i.gr-assets.com/images/S/compressed.ph...,1,1,23.04,Short Book,23,04,0
52456,2088519.Sex_at_the_Margins,"Sex at the Margins: Migration, Labour Markets ...",NaN,Laura María Agustín (Goodreads Author),4.11,This groundbreaking work explodes several myth...,English,9781842778609,"['Sex Work', 'Nonfiction', 'Feminism', 'Sociol...",[],Paperback,NaN,...,183,"['72', '73', '29', '5', '4']",95.0,[],https://i.gr-assets.com/images/S/compressed.ph...,1,1,13.35,Short Book,13,35,0
52472,12395883-unbelievable,Unbelievable,Port Fare #2,Sherry Gammon (Goodreads Author),4.16,Lilah Lopez Dreser's in town to take care of u...,English,9781477594247,"['Romance', 'Young Adult', 'Contemporary', 'Co...",[],Paperback,NaN,...,1028,"['442', '384', '142', '48', '12']",94.0,"['Port Fare, New York (United States)']",https://i.gr-assets.com/images/S/compressed.ph...,0,1,19.18,Short Book,19,18,0

In [27]:
df['price'] = np.log1p(df['price']) #log trasformation for outliners

In [28]:
# df['price'].hist()

In [29]:
df.isnull().sum()
df['likedPercent'].skew()#since skwenes is <-1 use median

np.float64(-2.563473312840859)

In [30]:
df['likedPercent']=df['likedPercent'].fillna(df['likedPercent'].median())
df['publishDate'].isnull().sum()

np.int64(880)

In [31]:
df['publishDate']=pd.to_datetime(df['publishDate'],errors='coerce')

C:\Users\hp\AppData\Local\Temp\ipykernel_884\774288222.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['publishDate']=pd.to_datetime(df['publishDate'],errors='coerce')

In [32]:
df['publishDate'].describe()
df['publishDate'].nlargest(20)

67      2075-06-28
548     2074-07-12
77      2073-03-28
117     2072-03-01
779     2069-10-28
12      2064-10-07
72      2063-02-01
535     2062-10-28
562     2062-08-01
218     2057-10-28
421     2052-12-01
354     2050-10-28
4239    2020-10-27
29165   2020-10-17
21272   2020-10-15
44852   2020-10-10
21270   2020-10-07
5572    2020-10-06
21022   2020-10-06
21269   2020-10-06
Name: publishDate, dtype: datetime64[us]

In [33]:
filr=df['publishDate']>'2020-10-27'

In [34]:
df.loc[filr,'publishDate']= pd.NaT

In [35]:
#replacing with the most common date...

df['publishDate'].value_counts()

publishDate
2008-01-01    319
2010-01-01    310
2007-01-01    288
2009-01-01    285
2006-01-01    283
             ...
1983-10-31      1
2009-06-10      1
2008-07-16      1
1983-02-24      1
2011-08-21      1
Name: count, Length: 8644, dtype: int64

In [36]:
#replacing  the nan with most common date
df['publishDate']=df['publishDate'].fillna('2008-01-01')

In [37]:
df['publishDate']=pd.to_datetime(df['publishDate'])

In [38]:
df['publishDate']

0       2008-09-14
1       2004-09-28
2       2006-05-23
3       2000-10-10
4       2006-09-06
           ...
52473   2011-05-28
52474   2011-08-05
52475   2011-03-18
52476   2011-09-01
52477   2011-05-08
Name: publishDate, Length: 52478, dtype: datetime64[us]

In [39]:
df['firstPublishDate'].isnull().sum()

np.int64(21326)

In [40]:
pd.set_option('display.max_column',28)
df

,bookId,title,series,author,rating,description,language,isbn,genres,characters,bookFormat,edition,pages,publisher,...,firstPublishDate,awards,numRatings,ratingsByStars,likedPercent,setting,coverImg,bbeScore,bbeVotes,price,length,first,sencond,third
0,2767052-the-hunger-games,The Hunger Games,The Hunger Games #1,Suzanne Collins,4.33,WINNING MEANS FAME AND FORTUNE.LOSING MEANS CE...,English,9780439023481,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...","['Katniss Everdeen', 'Peeta Mellark', 'Cato (H...",Hardcover,First Edition,374,Scholastic Press,...,NaN,['Locus Award Nominee for Best Young Adult Boo...,6376780,"['3444695', '1921313', '745221', '171994', '93...",96.0,"['District 12, Panem', 'Capitol, Panem', 'Pane...",https://i.gr-assets.com/images/S/compressed.ph...,2993816,30516,1.806648,Short Book,5,09,0
1,2.Harry_Potter_and_the_Order_of_the_Phoenix,Harry Potter and the Order of the Phoenix,Harry Potter #5,"J.K. Rowling, Mary GrandPré (Illustrator)",4.50,There is a door at the end of a silent corrido...,English,9780439358071,"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...","['Sirius Black', 'Draco Malfoy', 'Ron Weasley'...",Paperback,US Edition,870,Scholastic Inc.,...,06/21/03,['Bram Stoker Award for Works for Young Reader...,2507623,"['1593642', '637516', '222366', '39573', '14526']",98.0,['Hogwarts School of Witchcraft and Wizardry (...,https://i.gr-assets.com/images/S/compressed.ph...,2632233,26923,2.125848,Long Book,7,38,0
2,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,To Kill a Mockingbird,Harper Lee,4.28,The unforgettable novel of a childhood in a sl...,English,9999999999999,"['Classics', 'Fiction', 'Historical Fiction', ...","['Scout Finch', 'Atticus Finch', 'Jem Finch', ...",Paperback,NaN,324,Harper Perennial Modern Classics,...,07/11/60,"['Pulitzer Prize for Fiction (1961)', 'Audie A...",4501075,"['2363896', '1333153', '573280', '149952', '80...",95.0,"['Maycomb, Alabama (United States)']",https://i.gr-assets.com/images/S/compressed.ph...,2269402,23328,1.824549,Short Book,NaN,0,0
3,1885.Pride_and_Prejudice,Pride and Prejudice,NaN,"Jane Austen, Anna Quindlen (Introduction)",4.26,Alternate cover edition of ISBN 9780679783268S...,English,9999999999999,"['Classics', 'Fiction', 'Romance', 'Historical...","['Mr. Bennet', 'Mrs. Bennet', 'Jane Bennet', '...",Paperback,"Modern Library Classics, USA / CAN",279,Modern Library,...,01/28/13,[],2998241,"['1617567', '816659', '373311', '113934', '767...",94.0,"['United Kingdom', 'Derbyshire, England (Unite...",https://i.gr-assets.com/images/S/compressed.ph...,1983116,20452,1.824549,Short Book,NaN,0,0
4,41865.Twilight,Twilight,The Twilight Saga #1,Stephenie Meyer,3.60,About three things I was absolutely positive.\...,English,9780316015844,"['Young Adult', 'Fantasy', 'Romance', 'Vampire...","['Edward Cullen', 'Jacob Black', 'Laurent', 'R...",Paperback,NaN,501,"Little, Brown and Company",...,10/05/05,"['Georgia Peach Book Award (2007)', 'Buxtehude...",4964519,"['1751460', '1113682', '1008686', '542017', '5...",78.0,"['Forks, Washington (United States)', 'Phoenix...",https://i.gr-assets.com/images/S/compressed.ph...,1459448,14874,1.131402,Standard Book,2,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52473,11492014-fractured,Fractured,Fateful #2,Cheri Schmidt (Goodreads Author),4.00,The Fateful Trilogy continues with Fractured. ...,English,2940012616562,"['Vampires', 'Paranormal', 'Young Adult', 'Rom...",[],Nook,NaN,0,Cheri Schmidt,...,NaN,[],871,"['311', '310', '197', '42', '11']",94.0,[],https://i.gr-assets.com/images/S/compressed.ph...,0,1,1.824549,Short Book,NaN,0,0
52474,11836711-anasazi,Anasazi,Sense of Truth #2,Emma Michaels,4.19,"'Anasazi', sequel to 'The Thirteenth Chime' by...",English,9999999999999,"['Mystery', 'Young Adult']",[],Paperback,First Edition,190,Bokheim Publishing,...,August 3rd 2011,[],37,"['16', '14', '5', '2', '0']",95.0,[],https://i.gr-assets.com/images/S/compressed.ph...,0,1,1.824549,Short Book,NaN,0,0
52475,10815662-marked,Marked,Soul Guardians #1,Kim Richardson (Goodreads Author),3.70,--READERS FAVORITE AWARDS WINNER 2011--Sixteen...,English,9781461017097,"['Fantasy', 'Young Adult', 'Paranormal', 'Ange...",[],Paperback,NaN,280,CreateSpace,...,March 15th 2011,"[""Readers' Favorite Book Award (2011)""]",6674,"['2109', '1868', '1660', '647', '390']",84.0,[],https://i.gr-assets.com/images/S/compressed.ph...,0,1,2.124654,Short Book,7,37,0
52476,11330278-wayward-son,Wayward Son,NaN,"Tom Pollack (Goodreads Author), John Loftus (G...",3.85,A POWERFUL TREMOR UNEARTHS AN ANCIENT SECRETBu...,English,9781450755634,"['Fiction', 'Mystery', 'Historical Fiction', '...",[],Paperback,1st edition,507,Cascada Productions,...,April 5th 2011,[],238,"['77', '78', '59', '19', '5']",90.0,[],https://i.gr-assets.com/images/S/compressed.ph...,0,1,1.350667,Standard Book,2,86,0
52477,10991547-daughter-of-helaman,Daughter of Helaman,Stripling Warrior #1,Misty Moncur (Goodreads Author),4.02,Fighting in Helaman's army is Keturah's deepes...,English,9781599554976,"['Lds Fiction', 'Historical Fiction', 'Young A...",[],Paperback,NaN,201,Bonneville,...,NaN,[],246,"['106', '73', '42', '17', '8']",90.0,[],https://i.gr-assets.com/images/S/compressed.ph...,0,1,1.824549,Short Book,5,20,0

In [41]:
df['description'].isnull().sum()

np.int64(1338)

In [42]:
df['description'].fillna('No Discription',inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_884\3955308777.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['description'].fillna('No Discription',inplace=True)

0        WINNING MEANS FAME AND FORTUNE.LOSING MEANS CE...
1        There is a door at the end of a silent corrido...
2        The unforgettable novel of a childhood in a sl...
3        Alternate cover edition of ISBN 9780679783268S...
4        About three things I was absolutely positive.\...
                               ...
52473    The Fateful Trilogy continues with Fractured. ...
52474    'Anasazi', sequel to 'The Thirteenth Chime' by...
52475    --READERS FAVORITE AWARDS WINNER 2011--Sixteen...
52476    A POWERFUL TREMOR UNEARTHS AN ANCIENT SECRETBu...
52477    Fighting in Helaman's army is Keturah's deepes...
Name: description, Length: 52478, dtype: str

In [43]:
df

,bookId,title,series,author,rating,description,language,isbn,genres,characters,bookFormat,edition,pages,publisher,...,firstPublishDate,awards,numRatings,ratingsByStars,likedPercent,setting,coverImg,bbeScore,bbeVotes,price,length,first,sencond,third
0,2767052-the-hunger-games,The Hunger Games,The Hunger Games #1,Suzanne Collins,4.33,WINNING MEANS FAME AND FORTUNE.LOSING MEANS CE...,English,9780439023481,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...","['Katniss Everdeen', 'Peeta Mellark', 'Cato (H...",Hardcover,First Edition,374,Scholastic Press,...,NaN,['Locus Award Nominee for Best Young Adult Boo...,6376780,"['3444695', '1921313', '745221', '171994', '93...",96.0,"['District 12, Panem', 'Capitol, Panem', 'Pane...",https://i.gr-assets.com/images/S/compressed.ph...,2993816,30516,1.806648,Short Book,5,09,0
1,2.Harry_Potter_and_the_Order_of_the_Phoenix,Harry Potter and the Order of the Phoenix,Harry Potter #5,"J.K. Rowling, Mary GrandPré (Illustrator)",4.50,There is a door at the end of a silent corrido...,English,9780439358071,"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...","['Sirius Black', 'Draco Malfoy', 'Ron Weasley'...",Paperback,US Edition,870,Scholastic Inc.,...,06/21/03,['Bram Stoker Award for Works for Young Reader...,2507623,"['1593642', '637516', '222366', '39573', '14526']",98.0,['Hogwarts School of Witchcraft and Wizardry (...,https://i.gr-assets.com/images/S/compressed.ph...,2632233,26923,2.125848,Long Book,7,38,0
2,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,To Kill a Mockingbird,Harper Lee,4.28,The unforgettable novel of a childhood in a sl...,English,9999999999999,"['Classics', 'Fiction', 'Historical Fiction', ...","['Scout Finch', 'Atticus Finch', 'Jem Finch', ...",Paperback,NaN,324,Harper Perennial Modern Classics,...,07/11/60,"['Pulitzer Prize for Fiction (1961)', 'Audie A...",4501075,"['2363896', '1333153', '573280', '149952', '80...",95.0,"['Maycomb, Alabama (United States)']",https://i.gr-assets.com/images/S/compressed.ph...,2269402,23328,1.824549,Short Book,NaN,0,0
3,1885.Pride_and_Prejudice,Pride and Prejudice,NaN,"Jane Austen, Anna Quindlen (Introduction)",4.26,Alternate cover edition of ISBN 9780679783268S...,English,9999999999999,"['Classics', 'Fiction', 'Romance', 'Historical...","['Mr. Bennet', 'Mrs. Bennet', 'Jane Bennet', '...",Paperback,"Modern Library Classics, USA / CAN",279,Modern Library,...,01/28/13,[],2998241,"['1617567', '816659', '373311', '113934', '767...",94.0,"['United Kingdom', 'Derbyshire, England (Unite...",https://i.gr-assets.com/images/S/compressed.ph...,1983116,20452,1.824549,Short Book,NaN,0,0
4,41865.Twilight,Twilight,The Twilight Saga #1,Stephenie Meyer,3.60,About three things I was absolutely positive.\...,English,9780316015844,"['Young Adult', 'Fantasy', 'Romance', 'Vampire...","['Edward Cullen', 'Jacob Black', 'Laurent', 'R...",Paperback,NaN,501,"Little, Brown and Company",...,10/05/05,"['Georgia Peach Book Award (2007)', 'Buxtehude...",4964519,"['1751460', '1113682', '1008686', '542017', '5...",78.0,"['Forks, Washington (United States)', 'Phoenix...",https://i.gr-assets.com/images/S/compressed.ph...,1459448,14874,1.131402,Standard Book,2,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52473,11492014-fractured,Fractured,Fateful #2,Cheri Schmidt (Goodreads Author),4.00,The Fateful Trilogy continues with Fractured. ...,English,2940012616562,"['Vampires', 'Paranormal', 'Young Adult', 'Rom...",[],Nook,NaN,0,Cheri Schmidt,...,NaN,[],871,"['311', '310', '197', '42', '11']",94.0,[],https://i.gr-assets.com/images/S/compressed.ph...,0,1,1.824549,Short Book,NaN,0,0
52474,11836711-anasazi,Anasazi,Sense of Truth #2,Emma Michaels,4.19,"'Anasazi', sequel to 'The Thirteenth Chime' by...",English,9999999999999,"['Mystery', 'Young Adult']",[],Paperback,First Edition,190,Bokheim Publishing,...,August 3rd 2011,[],37,"['16', '14', '5', '2', '0']",95.0,[],https://i.gr-assets.com/images/S/compressed.ph...,0,1,1.824549,Short Book,NaN,0,0
52475,10815662-marked,Marked,Soul Guardians #1,Kim Richardson (Goodreads Author),3.70,--READERS FAVORITE AWARDS WINNER 2011--Sixteen...,English,9781461017097,"['Fantasy', 'Young Adult', 'Paranormal', 'Ange...",[],Paperback,NaN,280,CreateSpace,...,March 15th 2011,"[""Readers' Favorite Book Award (2011)""]",6674,"['2109', '1868', '1660', '647', '390']",84.0,[],https://i.gr-assets.com/images/S/compressed.ph...,0,1,2.124654,Short Book,7,37,0
52476,11330278-wayward-son,Wayward Son,NaN,"Tom Pollack (Goodreads Author), John Loftus (G...",3.85,A POWERFUL TREMOR UNEARTHS AN ANCIENT SECRETBu...,English,9781450755634,"['Fiction', 'Mystery', 'Historical Fiction', '...",[],Paperback,1st edition,507,Cascada Productions,...,April 5th 2011,[],238,"['77', '78', '59', '19', '5']",90.0,[],https://i.gr-assets.com/images/S/compressed.ph...,0,1,1.350667,Standard Book,2,86,0
52477,10991547-daughter-of-helaman,Daughter of Helaman,Stripling Warrior #1,Misty Moncur (Goodreads Author),4.02,Fighting in Helaman's army is Keturah's deepes...,English,9781599554976,"['Lds Fiction', 'Historical Fiction', 'Young A...",[],Paperback,NaN,201,Bonneville,...,NaN,[],246,"['106', '73', '42', '17', '8']",90.0,[],https://i.gr-assets.com/images/S/compressed.ph...,0,1,1.824549,Short Book,5,20,0

In [44]:
df['characters'].head(50)

0     ['Katniss Everdeen', 'Peeta Mellark', 'Cato (H...
1     ['Sirius Black', 'Draco Malfoy', 'Ron Weasley'...
2     ['Scout Finch', 'Atticus Finch', 'Jem Finch', ...
3     ['Mr. Bennet', 'Mrs. Bennet', 'Jane Bennet', '...
4     ['Edward Cullen', 'Jacob Black', 'Laurent', 'R...
5     ['Liesel Meminger', 'Hans Hubermann', 'Rudy St...
6     ['Snowball', 'Napoleon', 'Clover', 'Boxer', 'O...
7     ['Polly', 'Aslan', 'Lucy Pevensie', 'Edmund Pe...
8     ['Frodo Baggins', 'Gandalf', 'Bilbo Baggins', ...
9     ["Scarlett O'Hara", 'Rhett Butler', 'Ashley Wi...
10    ['Hazel Grace Lancaster', 'Augustus Waters', '...
11    ['Zaphod Beeblebrox', 'Arthur Dent', 'Ford Pre...
12                                                   []
13    ['Heathcliff', 'Catherine Earnshaw', 'Edgar Li...
14    ['Sophie Neveu', 'Robert Langdon', 'Sir Leigh ...
15    ['Sayuri Nitta', 'Mr. Bekku', 'Ichiro Tanaka',...
16    ['Basil Hallward', 'Lord Henry Wotton', 'Sibyl...
17    ['The Hatter (Lewis Carroll)', 'The Queen of H...
18    ['Jane Eyre', 'Bertha Mason', 'Grace Poole', '...
19    ['Jean Valjean', 'Javert', 'Cosette', 'Fantine...
20    ['Guy Montag', 'Norman Corwin', 'Clarisse McCl...
21    ['Albert', 'Drew Leighton (Divergent)', 'Eric ...
22    ['Ralph', 'Piggy', 'Roger', 'Jack Merridew', '...
23    ['Romeo Montague', 'Juliet Capulet', 'Tybalt',...
24             ['Santiago', 'Alchemist', 'Melchizedek']
25    ['Rodion Romanovich Raskolnikov', 'Porfiry Pet...
26    ['Bill', 'Patrick Grogan', 'Charlie Scorsoni (...
27    ['Nick Carraway', 'Jay Gatsby', 'Daisy Buchana...
28    ['Alexander "Alec" Lightwood', 'Jonathan "Jace...
29    ['Dink', 'Bernard', 'Valentine Wiggin', 'Peter...
30    ['Constantine Bates', 'Eugenia “Skeeter” Phela...
31    ['Marilla Cuthbert', 'Matthew Cuthbert', 'Dian...
32    ['Draco Malfoy', 'Ron Weasley', 'Petunia Dursl...
33          ['Le Petit Prince', 'La rose', 'Le renard']
34    ['Fern', 'Avery', 'Charlotte', 'Wilbur', 'Temp...
35    ['George Milton', 'Lennie Small', 'Candy', 'Cu...
36    ['Henry DeTamble', 'Clare Abshire', 'Gomez', '...
37    ['Jonathan Harker', 'Lucy Westenra', 'Abraham ...
38    ['John (Brave New World)', 'Bernard Marx', 'Le...
39    ['Úrsula Iguarán', 'Remedios Moscote', 'Remedi...
40    ['Holden Caulfield', 'Robert Ackley', 'Stradla...
41    ['Buttercup', 'Westley', 'Prince Humperdinck',...
42    ['Annabeth Chase', 'Grover Underwood', 'Luke C...
43    ['Mary Lennox', 'Colin Craven', 'Dickon Sowerb...
44              ['Laila', 'Mariam', 'Rasheed', 'Tariq']
45    ['Meg Murry', 'Charles Wallace Murry', "Calvin...
46    ['Brandon Stark', 'Catelyn Stark', 'Tyrion Lan...
47    ['Huckleberry Finn', 'Tom Sawyer', 'Jim Upton'...
48    ['Susie Salmon', 'Clarissa', 'Holly', 'Jack Sa...
49    ['Ponyboy Curtis', 'Sodapop Curtis', 'Darrel "...
Name: characters, dtype: str

In [45]:
df['characters'].nunique()

12448

In [46]:
filt =df['characters'] == '[]'

In [47]:
df[filt]

,bookId,title,series,author,rating,description,language,isbn,genres,characters,bookFormat,edition,pages,publisher,...,firstPublishDate,awards,numRatings,ratingsByStars,likedPercent,setting,coverImg,bbeScore,bbeVotes,price,length,first,sencond,third
12,370493.The_Giving_Tree,The Giving Tree,NaN,Shel Silverstein,4.37,"""Once there was a tree...and she loved a littl...",English,9780060256654,"['Childrens', 'Picture Books', 'Classics', 'Fi...",[],Hardcover,NaN,64,HarperCollins Publishers,...,10/28/64,[],905731,"['556142', '204347', '94819', '27950', '22473']",94.0,[],https://i.gr-assets.com/images/S/compressed.ph...,1021534,10594,1.769855,Short Book,4,87,0
97,23919.The_Complete_Stories_and_Poems,The Complete Stories and Poems,NaN,Edgar Allan Poe,4.38,This single volume brings together all of Poe'...,English,9780385074070,"['Classics', 'Poetry', 'Horror', 'Fiction', 'S...",[],Hardcover,NaN,821,"Doubleday & Company, Inc.",...,10/28/49,[],220153,"['122549', '66630', '24609', '4284', '2081']",97.0,['United States of America'],https://i.gr-assets.com/images/S/compressed.ph...,218309,2533,1.835776,Standard Book,5,27,0
116,70401.On_the_Road,On the Road,Duluoz Legend,Jack Kerouac,3.62,A quintessential novel of America & the Beat G...,English,9780140042597,"['Classics', 'Fiction', 'Travel', 'Literature'...",[],Paperback,NaN,307,Penguin Books,...,09/05/57,['Grammy Award Nominee for Best Spoken Word Al...,348767,"['91609', '109458', '88737', '40359', '18604']",83.0,[],https://i.gr-assets.com/images/S/compressed.ph...,140738,1595,1.068153,Short Book,1,91,0
121,4948.The_Very_Hungry_Caterpillar,The Very Hungry Caterpillar,NaN,Eric Carle,4.30,"THE all-time classic story, from generation to...",English,9780241003008,"['Picture Books', 'Childrens', 'Fiction', 'Cla...",[],Board book,NaN,26,Puffin Books,...,06/03/69,['California Young Readers Medal Nominee for P...,396110,"['228021', '90789', '53120', '15051', '9129']",94.0,[],https://i.gr-assets.com/images/S/compressed.ph...,137241,1601,1.229641,Short Book,2,42,0
143,114345.The_Little_House_Collection,The Little House Collection,Little House #1-9,"Laura Ingalls Wilder, Garth Williams (Illustra...",4.34,This nine-book paperback box set of the classi...,English,9780060529963,"['Classics', 'Historical Fiction', 'Childrens'...",[],Boxed Set,Box Set,1,Avon Books,...,10/28/71,[],141514,"['78697', '40270', '16803', '3312', '2432']",96.0,[],https://i.gr-assets.com/images/S/compressed.ph...,115088,1361,1.824549,Short Book,NaN,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52473,11492014-fractured,Fractured,Fateful #2,Cheri Schmidt (Goodreads Author),4.00,The Fateful Trilogy continues with Fractured. ...,English,2940012616562,"['Vampires', 'Paranormal', 'Young Adult', 'Rom...",[],Nook,NaN,0,Cheri Schmidt,...,NaN,[],871,"['311', '310', '197', '42', '11']",94.0,[],https://i.gr-assets.com/images/S/compressed.ph...,0,1,1.824549,Short Book,NaN,0,0
52474,11836711-anasazi,Anasazi,Sense of Truth #2,Emma Michaels,4.19,"'Anasazi', sequel to 'The Thirteenth Chime' by...",English,9999999999999,"['Mystery', 'Young Adult']",[],Paperback,First Edition,190,Bokheim Publishing,...,August 3rd 2011,[],37,"['16', '14', '5', '2', '0']",95.0,[],https://i.gr-assets.com/images/S/compressed.ph...,0,1,1.824549,Short Book,NaN,0,0
52475,10815662-marked,Marked,Soul Guardians #1,Kim Richardson (Goodreads Author),3.70,--READERS FAVORITE AWARDS WINNER 2011--Sixteen...,English,9781461017097,"['Fantasy', 'Young Adult', 'Paranormal', 'Ange...",[],Paperback,NaN,280,CreateSpace,...,March 15th 2011,"[""Readers' Favorite Book Award (2011)""]",6674,"['2109', '1868', '1660', '647', '390']",84.0,[],https://i.gr-assets.com/images/S/compressed.ph...,0,1,2.124654,Short Book,7,37,0
52476,11330278-wayward-son,Wayward Son,NaN,"Tom Pollack (Goodreads Author), John Loftus (G...",3.85,A POWERFUL TREMOR UNEARTHS AN ANCIENT SECRETBu...,English,9781450755634,"['Fiction', 'Mystery', 'Historical Fiction', '...",[],Paperback,1st edition,507,Cascada Productions,...,April 5th 2011,[],238,"['77', '78', '59', '19', '5']",90.0,[],https://i.gr-assets.com/images/S/compressed.ph...,0,1,1.350667,Standard Book,2,86,0
52477,10991547-daughter-of-helaman,Daughter of Helaman,Stripling Warrior #1,Misty Moncur (Goodreads Author),4.02,Fighting in Helaman's army is Keturah's deepes...,English,9781599554976,"['Lds Fiction', 'Historical Fiction', 'Young A...",[],Paperback,NaN,201,Bonneville,...,NaN,[],246,"['106', '73', '42', '17', '8']",90.0,[],https://i.gr-assets.com/images/S/compressed.ph...,0,1,1.824549,Short Book,5,20,0

In [48]:
df['characters']=df['characters'].str.replace('[]','Not available')

In [49]:
df['characters']=df['characters'].str.replace('[',' ')

In [50]:
df['characters']=df['characters'].str.replace(']',' ')

In [51]:
df['characters'].head(50)

0      'Katniss Everdeen', 'Peeta Mellark', 'Cato (H...
1      'Sirius Black', 'Draco Malfoy', 'Ron Weasley'...
2      'Scout Finch', 'Atticus Finch', 'Jem Finch', ...
3      'Mr. Bennet', 'Mrs. Bennet', 'Jane Bennet', '...
4      'Edward Cullen', 'Jacob Black', 'Laurent', 'R...
5      'Liesel Meminger', 'Hans Hubermann', 'Rudy St...
6      'Snowball', 'Napoleon', 'Clover', 'Boxer', 'O...
7      'Polly', 'Aslan', 'Lucy Pevensie', 'Edmund Pe...
8      'Frodo Baggins', 'Gandalf', 'Bilbo Baggins', ...
9      "Scarlett O'Hara", 'Rhett Butler', 'Ashley Wi...
10     'Hazel Grace Lancaster', 'Augustus Waters', '...
11     'Zaphod Beeblebrox', 'Arthur Dent', 'Ford Pre...
12                                        Not available
13     'Heathcliff', 'Catherine Earnshaw', 'Edgar Li...
14     'Sophie Neveu', 'Robert Langdon', 'Sir Leigh ...
15     'Sayuri Nitta', 'Mr. Bekku', 'Ichiro Tanaka',...
16     'Basil Hallward', 'Lord Henry Wotton', 'Sibyl...
17     'The Hatter (Lewis Carroll)', 'The Queen of H...
18     'Jane Eyre', 'Bertha Mason', 'Grace Poole', '...
19     'Jean Valjean', 'Javert', 'Cosette', 'Fantine...
20     'Guy Montag', 'Norman Corwin', 'Clarisse McCl...
21     'Albert', 'Drew Leighton (Divergent)', 'Eric ...
22     'Ralph', 'Piggy', 'Roger', 'Jack Merridew', '...
23     'Romeo Montague', 'Juliet Capulet', 'Tybalt',...
24              'Santiago', 'Alchemist', 'Melchizedek'
25     'Rodion Romanovich Raskolnikov', 'Porfiry Pet...
26     'Bill', 'Patrick Grogan', 'Charlie Scorsoni (...
27     'Nick Carraway', 'Jay Gatsby', 'Daisy Buchana...
28     'Alexander "Alec" Lightwood', 'Jonathan "Jace...
29     'Dink', 'Bernard', 'Valentine Wiggin', 'Peter...
30     'Constantine Bates', 'Eugenia “Skeeter” Phela...
31     'Marilla Cuthbert', 'Matthew Cuthbert', 'Dian...
32     'Draco Malfoy', 'Ron Weasley', 'Petunia Dursl...
33           'Le Petit Prince', 'La rose', 'Le renard'
34     'Fern', 'Avery', 'Charlotte', 'Wilbur', 'Temp...
35     'George Milton', 'Lennie Small', 'Candy', 'Cu...
36     'Henry DeTamble', 'Clare Abshire', 'Gomez', '...
37     'Jonathan Harker', 'Lucy Westenra', 'Abraham ...
38     'John (Brave New World)', 'Bernard Marx', 'Le...
39     'Úrsula Iguarán', 'Remedios Moscote', 'Remedi...
40     'Holden Caulfield', 'Robert Ackley', 'Stradla...
41     'Buttercup', 'Westley', 'Prince Humperdinck',...
42     'Annabeth Chase', 'Grover Underwood', 'Luke C...
43     'Mary Lennox', 'Colin Craven', 'Dickon Sowerb...
44               'Laila', 'Mariam', 'Rasheed', 'Tariq'
45     'Meg Murry', 'Charles Wallace Murry', "Calvin...
46     'Brandon Stark', 'Catelyn Stark', 'Tyrion Lan...
47     'Huckleberry Finn', 'Tom Sawyer', 'Jim Upton'...
48     'Susie Salmon', 'Clarissa', 'Holly', 'Jack Sa...
49     'Ponyboy Curtis', 'Sodapop Curtis', 'Darrel "...
Name: characters, dtype: str

In [52]:
df['characters']=df['characters'].str.split(',')

In [53]:
df['characters']

0        [ 'Katniss Everdeen',  'Peeta Mellark',  'Cato...
1        [ 'Sirius Black',  'Draco Malfoy',  'Ron Weasl...
2        [ 'Scout Finch',  'Atticus Finch',  'Jem Finch...
3        [ 'Mr. Bennet',  'Mrs. Bennet',  'Jane Bennet'...
4        [ 'Edward Cullen',  'Jacob Black',  'Laurent',...
                               ...
52473                                      [Not available]
52474                                      [Not available]
52475                                      [Not available]
52476                                      [Not available]
52477                                      [Not available]
Name: characters, Length: 52478, dtype: object

In [54]:
df['numberofchar']=len(df.loc[:,'characters'])

In [55]:
df.drop(columns=['numberofchar','first','sencond','third'],inplace=True)

In [56]:

df['numofchar']=df['characters'].apply(lambda x:len(x))

In [57]:
df['numofchar']

0        23
1        44
2        14
3        24
4        17
         ..
52473     1
52474     1
52475     1
52476     1
52477     1
Name: numofchar, Length: 52478, dtype: int64

In [58]:
filt2= df['numofchar']==1

In [59]:
df.loc[filt2,'numofchar']=0

In [60]:
df['numofchar'].describe()

count    52478.000000
mean         1.373928
std          6.885919
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max        669.000000
Name: numofchar, dtype: float64

In [61]:
filt3=df['numofchar']>50

In [62]:
df.loc[filt3,'numofchar'].count()

np.int64(56)

In [63]:
df.loc[filt3,['numofchar','series','title','characters']]

,numofchar,series,title,characters
71,61,Harry Potter #7,Harry Potter and the Deathly Hallows,"[ 'Sirius Black', 'Draco Malfoy', 'Ron Weasl..."
190,479,NaN,Ulysses,"[ 'Stephen Dedalus', 'Leopold Bloom', 'Mario..."
198,58,NaN,David Copperfield,"[ 'Richard Babley', 'Mr. Barkis', 'Mr. Chill..."
248,669,A Song of Ice and Fire #2,A Clash of Kings,"[ 'Brandon Stark', 'Catelyn Stark', 'Tyrion ..."
356,65,NaN,The Complete Novels,"[ 'Mr. Bennet', 'Mrs. Bennet', 'Jane Bennet'..."
722,140,NaN,Under the Dome,"[ 'Dale Barbara', 'Julia Shumway', 'James Re..."
752,90,NaN,Holy Bible: King James Version,"[ 'Barabbas', 'Lucifer', 'Moses (Bible)', '..."
1489,77,Wars of the Roses #8,Richard III,"[ 'Elizabeth of York', 'Elizabeth Woodville',..."
2184,58,Narratives of Empire #2,Lincoln,"[ 'Abraham Lincoln', 'Walt Whitman', 'Willia..."
2234,145,NaN,The 48 Laws of Power,"[ 'Xerxes I of Persia', 'Oedipus', 'Cardinal..."
2626,54,Warriors #6,The Darkest Hour,"[ 'Graystripe', 'Sandstorm', 'Whitestorm', ..."
2672,51,Marvel Super Special #29,Tarzan of the Apes,"[ 'Tarzan', 'Jane Porter', 'Archimedes Q. Po..."
2951,52,Warriors #2,Fire and Ice,"[ 'Lionheart', 'Graystripe', 'Fireheart', '..."
3028,54,Warriors #3,Forest of Secrets,"[ 'Graystripe', 'Fireheart', 'Sandstorm', '..."
3259,55,Warriors #4,Rising Storm,"[ 'Graystripe', 'Fireheart', 'Sandstorm', '..."
3415,59,Warriors #5,A Dangerous Path,"[ 'Graystripe', 'Fireheart', 'Sandstorm', '..."
3499,634,The Wheel of Time #8,The Path of Daggers,"[ 'Birgitte Silverbow', ""Rand (aka Rand al'Th..."
4215,88,NaN,Mahabharata,"[ 'Dushashana', 'Bhimasena', 'Bhurisravas', ..."
6070,55,Luthiel's Song #1,Dreams of the Ringed Vale,"[ 'Luthiel', 'Othalas', 'Melkion', 'Mithord..."
6778,312,NaN,At Home: A Short History of Private Life,"[ 'Lon Don', 'Thomas John Gordon Marsham', '..."
7086,52,NaN,Life,"[ 'Richard Leher', 'Bill Gober', 'Dick Taylo..."
7873,56,Jack Ryan #4,The Cardinal of the Kremlin,"[ 'Mary Patricia Foley', 'Colonel Mikhail Sem..."
7996,54,Wars of the Roses #1,Richard II,"[ 'Henry Percy ""Hotspur""', 'Henry V of Englan..."
8418,55,Luthiel's Song #2,The War of Mists,"[ 'Luthiel', 'Othalas', 'Melkion', 'Mithord..."
9942,79,The Traitor Son Cycle #1,The Red Knight,"[ 'Royal Guard', 'Alcaeus Comnena', 'Skinch'..."
10573,61,Civil War (Collected Editions,Civil War: A Marvel Comics Event,"[ 'Scott Summers', 'Wolverine', 'Matt Murdoc..."
11474,73,Void #1,The Dreaming Void,"[ 'Edeard', 'Corrie-Lyn', 'Justine Burnelli'..."
11702,63,NaN,"Women, Race & Class","[ 'George Francis Train', 'Frederick Douglass..."
12786,66,NaN,Fire and Fury: Inside the Trump White House,"[ 'Bill Clinton', 'George W. Bush', 'Rudy Gi..."
13108,56,The Books of Magic #0,The Books of Magic,"[ 'Darkseid', 'Dream of the Endless', 'Zatan..."
13359,84,NaN,The Young Lions,"[ 'Michael Whiteacre', 'Hope Plowman', 'Chri..."
13669,78,NaN,"The Last Stand: Custer, Sitting Bull, and the ...","[ 'Alfred Terry', 'Frederick Benteen', 'Edwa..."
13736,64,The School for Good and Evil: The Camelot Year...,One True King,"[ 'Robin Hood', 'Agatha (SFGAE)', 'Sophie (S..."
14574,99,NaN,The Greek Myths,"[ 'Oedipus', 'Artemis (Goddess)', 'Demeter (..."
15020,52,Jeeves #2,The Inimitable Jeeves,"[ 'Reginald Jeeves', 'James Bates', 'Bertram..."
15296,54,NaN,Roughing It,"[ 'Samuel ""Mark Twain"" Clemens', 'Mr. Higbie'..."
15309,59,Vision (2015) (Collected Editions) #1,"The Vision, Volume 1: Little Worse Than A Man","[ 'Magneto', 'Barack Obama', 'Hercules (Marv..."
15418,62,Blandings Castle #3,Blandings Castle,"[ 'Clarence Threepwood', 'Sebastian Beach', ..."
15687,76,Auntie Mame #1,Auntie Mame: An Irreverent Escapade,"[ 'Frank Crowninshield', 'Condé Montrose Nast..."
15788,70,Stephen Fry's Great Mythology #1,Mythos: The Greek Myths Retold,"[ 'Artemis (Goddess)', 'Demeter (Goddess)', ..."
16834,60,The School for Good and Evil: The Camelot Year...,A Crystal of Time,"[ 'Robin Hood', 'King Arthur', 'Agatha (SFGA..."
23983,193,NaN,A Doctor in the House: The Memoirs of Tun Dr M...,"[ 'Dr Mahathir Mohamad', 'Tunku Abdul Rahman ..."
26310,137,NaN,Hitch 22: A Memoir,"[ 'Bill Clinton', 'Thomas Aquinas', 'George ..."
30851,52,Wars of the Roses #5,"Henry VI, Part 1","[ 'Richard de Beauchamp, 13th Earl of Warwick..."
32660,51,Jack Kirby's Fourth World #1,"Jack Kirby's Fourth World Omnibus, Vol. 1","[ 'Perry White', 'Darkseid', 'Oberon Kurtzbe..."
36528,80,Marvel Omnibus,Howard the Duck Omnibus,"[ 'Wonder Woman', 'Howard the Duck', 'Doctor..."
37150,324,NaN,Bulfinch's Mythology,"[ 'Thor (Norse Mythology)', 'Launcelot du Lac..."
37718,387,NaN,Nightmares and Dreamscapes,"[ 'Matt Knaide', 'Candy Kane', 'Andy Estes',..."
37822,84,Dreamsongs #1,"Dreamsongs, Volume I","[ 'Jad Rakkis', 'Squadmother Jolip', 'John K..."
37955,127,NaN,Arguably: Selected Essays,"[ 'Idi Amin', 'Alexander II of Russia', 'Kon..."
40098,342,NaN,Marvel Comics: The Untold Story,"[ 'Art Spiegelman', 'Andy Warhol', 'Steven S..."
42251,160,Man-Thing (1979) #1-11,The Man-Thing Omnibus,"[ 'Huckleberry Finn', 'Jim Upton', 'Matt Mur..."
45999,59,Dark #14,Dark Celebration,"[ 'Mikhail Dubrinsky', 'Raven Whitney', 'Jul..."
49601,53,Trouble #2,Deep in the Heart of Trouble,"[ 'Essie Spreckelmeyer', 'Tony Morgan', 'Ess..."
50797,69,NaN,Horse Soldiers: The Extraordinary Story of a B...,"[ 'General Doustoum', 'Mike Spann', 'Mitch N..."
51689,78,Wars of the Roses #3,"Henry IV, Part 2","[ 'Sir John Falstaff', 'Henry V of England', ..."

In [64]:
df.loc[df['numofchar']==479,'characters'].value_counts()

characters
[ 'Stephen Dedalus',  'Leopold Bloom',  'Marion "Molly" Bloom',  'Malachi "Buck" Mulligan',  'Mr. Garret Deasy',  'Bantam Lyons',  'Simon Dedalus',  'Myles Crawford',  'William Humble,  Earl of Dudley',  'Hugh "Blazes" Boylan',  'The Citizen',  'Gerty MacDowell',  'Mina Purefoy',  'John Corley',  'D.B. Murphy',  'Matthew Lenehan',  'Fr. Bernard Vaughan',  'James Fitzharris',  'Fanny Moody',  'Charles Manners',  'Haines',  'Thomas "Tommy" Caffrey',  'John "Jacky" Caffrey',  'Martha Clifford',  'Mr. Power',  'Patrick Dignam',  'Patrick Aloysius Dignam,  jnr.',  'Martin Cunningham',  'Fr. John Conmee',  'Bridget "Bridie" Kelly',  "J.J. O'Molloy",  'Mary Dedalus',  'George Russell',  'Stephen Daedalus',  'Stephen MacKenna',  'Mr Leopold Bloom',  "Mr Joseph M'Carthy Hynes",  'Mrs Marion Bloom',  'Mr Simon Dedalus',  'Alf Bergan',  'Buck Mulligan',  'Blazes Boylan',  'Mr Garrett Deasy',  'Mr Power',  'Millie Bloom',  'Boylan',  'Mr Paddy Dignam',  "Terence O'Ryan",  'Davy Byrne',  'Bob Doran',  'Mr Thomas Kernan',  'Ned Lambert',  'T. Lenehan',  'Mr O’madden Burke',  'Garrett Deasy',  'Mrs Josephine Breen',  'Benjamin Dollard',  "J. J. O'Molloy",  'John Eglinton',  'Mr V. Lynch',  'Edy Boardman',  'Tommy Caffrey',  'Cissy Caffrey',  'Jacky Caffrey',  'Mrs Bella Cohen',  'Richard Crookback',  'Richie Goulding',  'Walter Sexton',  'John Henry Menton',  'Sara (Sally) Goulding',  "Episode Twelve's Nameless Narrator",  'Mina Kennedy',  'Lydia Douce',  'Zoe Higgins',  'Mrs. Dignam',  'Paddy Dignam',  'Kitty Ricketts',  'Josie (Powell) Breen',  'Denis Breen',  'Dilly,  Katey,  Boody,  and Maggy Dedalus',  'Mr Cornelius Kelleher',  'Thomas W. Lyster',  'Joseph P. Nannetti',  'Florry Talbot',  'Tom Rochford',  'Barney Kiernan',  'Mr Fox',  'Mr Hornblower',  'Mother Grogan',  'Master Boardman',  'Mrs Stoer',  'Signor Maffei',  'Gerald Ward A.D.C.',  'Jacob Halliday',  'Joseph Glynn', ...]    1
Name: count, dtype: int64

In [65]:
df['awards'].head(50)

0     ['Locus Award Nominee for Best Young Adult Boo...
1     ['Bram Stoker Award for Works for Young Reader...
2     ['Pulitzer Prize for Fiction (1961)', 'Audie A...
3                                                    []
4     ['Georgia Peach Book Award (2007)', 'Buxtehude...
5     ['National Jewish Book Award for Children’s an...
6     ['Prometheus Hall of Fame Award (2011)', 'Retr...
7                                                    []
8                                                    []
9     ['Pulitzer Prize for Novel (1937)', 'National ...
10    ['Georgia Peach Book Award (2013)', 'Buxtehude...
11                                                   []
12                                                   []
13                                                   []
14    ['British Book Award for Book of the Year (200...
15                                                   []
16                                                   []
17                                                   []
18                                                   []
19                                                   []
20    ['Prometheus Hall of Fame Award (1984)', 'Geff...
21    ['Georgia Peach Book Award (2012)', 'South Car...
22                                                   []
23                                                   []
24    ['NBDB National Book Award Nominee for Transla...
25                                                   []
26                                                   []
27    ['Grammy Award Nominee for Best Spoken Word Al...
28    ['Locus Award Nominee for Best First Novel (20...
29    ['Hugo Award for Best Novel (1986)', 'Nebula A...
30    ['Orange Prize Nominee for Fiction Longlist (2...
31                                                   []
32    ["Mythopoeic Fantasy Award for Children's Lite...
33         ['Retro Hugo Award for Best Novella (2019)']
34    ['Newbery Medal Nominee (1953)', "George C. St...
35    ["New York Drama Critics' Circle Award for Bes...
36    ['Arthur C. Clarke Award Nominee (2005)', 'Ora...
37                                                   []
38                                                   []
39    ['Premio Internacional de Novela Rómulo Galleg...
40    ['Teen Read Award Nominee for Best All-Time-Fa...
41                                                   []
42    ["Young Readers' Choice Award (2008)", 'Books ...
43                 ['Lewis Carroll Shelf Award (1958)']
44    ['British Book Award for Best Read of the Year...
45    ['Newbery Medal (1963)', "Dorothy Canfield Fis...
46    ['Nebula Award Nominee for Best Novel (1997)',...
47                                                   []
48    ['Bram Stoker Award for Best First Novel (2002...
49    ['Books I Loved Best Yearly (BILBY) Awards for...
Name: awards, dtype: str

In [66]:
filraw=df['awards']=='[]'

In [67]:
filraw.value_counts()

awards
True     41864
False    10614
Name: count, dtype: int64

In [68]:
df['awards']=df['awards'].str.replace('[]','No awards')

In [69]:
df['awards']=df['awards'].str.replace('[',' ')
df['awards']=df['awards'].str.replace(']',' ')

In [70]:
df['awards']=df['awards'].str.split(',')

In [71]:
#getting how many awards a book have
df['numofawards']=df['awards'].apply(lambda x:len(x))

In [72]:
filt4=df['awards'].apply(lambda x:x[0]=='No awards')

In [73]:
df.loc[filt4,'numofawards']=None

In [74]:
(df['numofawards']>2).sum()
df.info()

<class 'pandas.DataFrame'>
Index: 52478 entries, 0 to 52477
Data columns (total 28 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   bookId            52478 non-null  str
 1   title             52476 non-null  str
 2   series            23470 non-null  str
 3   author            52478 non-null  str
 4   rating            52478 non-null  float64
 5   description       51140 non-null  str
 6   language          48672 non-null  str
 7   isbn              52478 non-null  str
 8   genres            52478 non-null  str
 9   characters        52478 non-null  object
 10  bookFormat        51005 non-null  str
 11  edition           4955 non-null   str
 12  pages             52478 non-null  int64
 13  publisher         48782 non-null  str
 14  publishDate       52478 non-null  datetime64[us]
 15  firstPublishDate  31152 non-null  str
 16  awards            52478 non-null  object
 17  numRatings        52478 non-null  int64
 18  ratingsByStars    52478 non-null  str
 19  likedPercent      52478 non-null  float64
 20  setting           52478 non-null  str
 21  coverImg          51873 non-null  str
 22  bbeScore          52478 non-null  int64
 23  bbeVotes          52478 non-null  int64
 24  price             52478 non-null  float64
 25  length            52478 non-null  str
 26  numofchar         52478 non-null  int64
 27  numofawards       10614 non-null  float64
dtypes: datetime64[us](1), float64(4), int64(5), object(2), str(16)
memory usage: 11.6+ MB

In [75]:
pd.set_option('display.max_rows',52477)

In [76]:
df['characters'].apply(type).value_counts()

characters
<class 'list'>    52478
Name: count, dtype: int64

In [77]:
df['setting']

0        ['District 12, Panem', 'Capitol, Panem', 'Pane...
1        ['Hogwarts School of Witchcraft and Wizardry (...
2                     ['Maycomb, Alabama (United States)']
3        ['United Kingdom', 'Derbyshire, England (Unite...
4        ['Forks, Washington (United States)', 'Phoenix...
                               ...
52473                                                   []
52474                                                   []
52475                                                   []
52476                                                   []
52477                                                   []
Name: setting, Length: 52478, dtype: str

In [78]:
df['characters']=df['characters'].apply(lambda x: None if x[0]=='Not available' else x)

In [79]:
df['characters']

0        [ 'Katniss Everdeen',  'Peeta Mellark',  'Cato...
1        [ 'Sirius Black',  'Draco Malfoy',  'Ron Weasl...
2        [ 'Scout Finch',  'Atticus Finch',  'Jem Finch...
3        [ 'Mr. Bennet',  'Mrs. Bennet',  'Jane Bennet'...
4        [ 'Edward Cullen',  'Jacob Black',  'Laurent',...
                               ...
52473                                                 None
52474                                                 None
52475                                                 None
52476                                                 None
52477                                                 None
Name: characters, Length: 52478, dtype: object

In [80]:
df.to_csv('aaditya_cleaned.csv')

In [82]:
df.loc[1, 'price']

np.float64(2.1258479144939915)